//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Student
    {
        public int id { get; set; }
        public string img { get; set; }
        public string name { get; set; }
        public string price { get; set; }
        public string des { get; set; }
        public string currency { get; set; }
        public string quantityInCart { get; set; }
        public string sum { get; set; }
        public string promo { get; set; }
        public string np { get; set; }
        public string category { get; set; }
    }
}
